import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vite-plus'

export default defineConfig({
  fmt: {
    semi: false,
    singleQuote: true,
    printWidth: 90,
  },
  lint: {
    plugins: [`oxc`, `typescript`, `unicorn`, `import`, `vitest`],
    options: { typeAware: true, typeCheck: true },
    categories: {
      correctness: `error`,
      suspicious: `error`,
      perf: `error`,
    },
    ignorePatterns: [`build/**`, `.svelte-kit/**`, `package/**`, `dist/**`],
    rules: {
      // Extra rules not in the enabled categories
      '@typescript-eslint/no-unused-vars': [
        `error`,
        { argsIgnorePattern: `^_`, varsIgnorePattern: `^_` },
      ],
      '@typescript-eslint/ban-ts-comment': `error`,
      '@typescript-eslint/no-explicit-any': `error`,
      '@typescript-eslint/await-thenable': `error`,
      '@typescript-eslint/consistent-type-imports': `error`,
      '@typescript-eslint/consistent-type-exports': `error`,
      '@typescript-eslint/no-deprecated': `error`,
      '@typescript-eslint/no-dynamic-delete': `error`,
      '@typescript-eslint/no-empty-object-type': `error`,
      '@typescript-eslint/no-floating-promises': `error`,
      '@typescript-eslint/no-import-type-side-effects': `error`,
      '@typescript-eslint/no-invalid-void-type': `error`,
      '@typescript-eslint/no-misused-promises': `error`,
      '@typescript-eslint/no-mixed-enums': `error`,
      '@typescript-eslint/no-non-null-asserted-optional-chain': `error`,
      '@typescript-eslint/no-non-null-assertion': `error`,
      '@typescript-eslint/no-require-imports': `error`,
      '@typescript-eslint/no-unnecessary-condition': `error`,
      '@typescript-eslint/only-throw-error': `error`,
      '@typescript-eslint/prefer-function-type': `error`,
      '@typescript-eslint/prefer-includes': `error`,
      '@typescript-eslint/prefer-string-starts-ends-with': `error`,
      '@typescript-eslint/prefer-nullish-coalescing': `error`,
      '@typescript-eslint/prefer-optional-chain': `error`,
      '@typescript-eslint/prefer-readonly': `error`,
      '@typescript-eslint/prefer-reduce-type-parameter': `error`,
      '@typescript-eslint/prefer-regexp-exec': `error`,
      '@typescript-eslint/prefer-find': `error`,
      '@typescript-eslint/prefer-ts-expect-error': `error`,
      '@typescript-eslint/restrict-plus-operands': `error`,
      '@typescript-eslint/return-await': `error`,
      '@typescript-eslint/strict-boolean-expressions': `error`,
      '@typescript-eslint/switch-exhaustiveness-check': `error`,
      '@typescript-eslint/unified-signatures': `error`,
      'array-callback-return': `error`,
      'no-eval': `error`,
      eqeqeq: `error`,
      'no-var': `error`,
      'no-throw-literal': `error`,
      'no-useless-rename': `error`,
      'no-self-compare': `error`,
      'no-template-curly-in-string': `error`,
      'no-constructor-return': `error`,
      'no-console': [`error`, { allow: [`warn`, `error`] }],
      'no-inner-declarations': `error`,
      'default-param-last': `error`,
      'guard-for-in': `error`,
      'prefer-object-has-own': `error`,
      'require-await': `error`,
      'no-useless-computed-key': `error`,
      'eslint-plugin-unicorn/no-useless-spread': `error`,
      'eslint-plugin-unicorn/prefer-string-replace-all': `error`,
      'eslint-plugin-unicorn/catch-error-name': `error`,
      'eslint-plugin-unicorn/prefer-set-has': `error`,
      'eslint-plugin-unicorn/prefer-array-find': `error`,
      'eslint-plugin-unicorn/prefer-dom-node-append': `error`,
      'eslint-plugin-unicorn/prefer-global-this': `error`,
      'eslint-plugin-unicorn/no-lonely-if': `error`,
      'eslint-plugin-unicorn/no-negated-condition': `error`,
      'eslint-plugin-unicorn/no-typeof-undefined': `error`,
      'eslint-plugin-unicorn/prefer-optional-catch-binding': `error`,
      'eslint-plugin-unicorn/no-length-as-slice-end': `error`,
      'eslint-plugin-unicorn/prefer-node-protocol': `error`,
      'eslint-plugin-unicorn/prefer-regexp-test': `error`,
      'eslint-plugin-unicorn/throw-new-error': `error`,
      'eslint-plugin-unicorn/prefer-includes': `error`,
      'eslint-plugin-unicorn/prefer-type-error': `error`,
      'eslint-plugin-unicorn/prefer-date-now': `error`,
      'eslint-plugin-unicorn/require-number-to-fixed-digits-argument': `error`,
      'eslint-plugin-unicorn/no-useless-promise-resolve-reject': `error`,
      'eslint-plugin-unicorn/custom-error-definition': `error`,
      'eslint-plugin-unicorn/require-array-join-separator': `error`,
      'eslint-plugin-import/first': `error`,
      'eslint-plugin-import/no-duplicates': `error`,
      'eslint-plugin-import/no-mutable-exports': `error`,
      'eslint-plugin-promise/no-multiple-resolved': `error`,
      'eslint-plugin-promise/no-return-in-finally': `error`,
      'eslint-plugin-promise/param-names': `error`,
      'eslint-plugin-promise/valid-params': `error`,
      'eslint-plugin-vitest/expect-expect': `error`,
      'eslint-plugin-vitest/prefer-each': `error`,
      'eslint-plugin-vitest/prefer-strict-boolean-matchers': `error`,
      'eslint-plugin-vitest/prefer-called-exactly-once-with': `error`,
      'eslint-plugin-vitest/require-awaited-expect-poll': `error`,
    },
  },
  staged: {
    '*.{js,ts,svelte,html,css,md,json,yaml}': `vp check --fix`,
    '*.{ts,svelte}': `sh -c 'npx svelte-kit sync && npx svelte-check-rs --threshold error'`,
    '*.test.ts': `sh -c '! grep -E "(test|describe)\\.only\\(" "$@"' --`,
  },
  plugins: [sveltekit()],

  test: {
    include: [`tests/vitest/**/*.test.ts`],
    environment: `jsdom`,
    css: true,
    coverage: {
      reporter: [`text`, `json-summary`],
    },
  },

  server: {
    fs: { allow: [`..`] }, // needed to import from $root
    port: 3000,
  },

  preview: {
    port: 3000,
  },

  build: {
    // Default cssTarget is chrome111 which doesn't support light-dark(),
    cssTarget: `esnext`, // causing LightningCSS to polyfill it with broken space toggles
  },

  resolve: {
    // Vitest component tests need Svelte's browser build for mount().
    conditions: [`browser`],
  },
})
