name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  tests:
    uses: janosh/workflows/.github/workflows/npm-test.yml@main
    with:
      install-e2e: npx playwright install chromium
